services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 123456
      ORACLE_DATABASE: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - ./oracle-data:/opt/oracle/oradata
      - ./data:/opt/oracle/dump
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  ora2pg:
    image: georgmoser/ora2pg:latest
    container_name: ora2pg-migration
    environment:
      - ORACLE_HOME=/usr/lib/oracle/19.26/client64
      - LD_LIBRARY_PATH=/usr/lib/oracle/19.26/client64/lib
      - TNS_ADMIN=/config
      # Không set NLS_LANG để tránh lỗi ORA-12705
    volumes:
      - ./ora2pg/config:/config:ro
      - ./migrate-data/output:/data
      - ./migrate-data/logs:/logs
    networks:
      - default
    depends_on:
      - oracle
      - postgres
    restart: unless-stopped
    # Giữ container chạy để có thể exec vào chạy migration khi cần
    command: tail -f /dev/null